export const typography = {
    custom_Display1_Bold: {
        fontSize: '36px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Display1_Medium: {
        fontSize: '36px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Display1_Regular: {
        fontSize: '36px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Display2_Bold: {
        fontSize: '32px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Display2_Medium: {
        fontSize: '32px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Display2_Regular: {
        fontSize: '32px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Title1_Bold: {
        fontSize: '28px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Title1_Medium: {
        fontSize: '28px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Title1_Regular: {
        fontSize: '28px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Title2_Bold: {
        fontSize: '24px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Title2_Medium: {
        fontSize: '24px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Title2_Regular: {
        fontSize: '24px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    HeadLine1_Bold: {
        fontSize: '20px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    HeadLine1_Medium: {
        fontSize: '20px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    HeadLine1_Regular: {
        fontSize: '20px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    HeadLine2_Bold: {
        fontSize: '18px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    HeadLine2_Medium: {
        fontSize: '18px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    HeadLine2_Regular: {
        fontSize: '18px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Body1_Bold: {
        fontSize: '16px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Body1_Medium: {
        fontSize: '16px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Body1_Regular: {
        fontSize: '16px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },    
    Body2_Bold: {
        fontSize: '14px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Body2_Medium: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Body2_Regular: {
        fontSize: '14px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },

    custom_Label_Bold: {
        fontSize: '14px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Label_Medium: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    custom_Label_Regular: {
        fontSize: '14px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Caption1_Bold: {
        fontSize: '12px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Caption1_Medium: {
        fontSize: '12px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Caption1_Regular: {
        fontSize: '12px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },

    Caption2_Bold: {
        fontSize: '10px',
        fontWeight: 700,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Caption2_Medium: {
        fontSize: '10px',
        fontWeight: 500,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
    Caption2_Regular: {
        fontSize: '10px',
        fontWeight: 400,
        lineHeight: 1.3,
        fontFamily: "Pretendard",
    },
}